; generated by binc — works as C, acts as Metal
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32"
target triple = "air64_v29-apple-macosx27.0.0"


define void @blend(float addrspace(1)* nocapture noundef %_a, float addrspace(1)* nocapture noundef %_b, float addrspace(1)* nocapture noundef %_out, i32 noundef %_id) local_unnamed_addr #0 {
  %t0 = zext i32 %_id to i64
  %t1 = getelementptr inbounds float, float addrspace(1)* %_a, i64 %t0
  %t2 = load float, float addrspace(1)* %t1, align 4
  %t3 = fmul fast float %t2, 5.000000e-01
  %t4 = getelementptr inbounds float, float addrspace(1)* %_b, i64 %t0
  %t5 = load float, float addrspace(1)* %t4, align 4
  %t6 = fmul fast float %t5, 5.000000e-01
  %t7 = fadd fast float %t3, %t6
  %t8 = getelementptr inbounds float, float addrspace(1)* %_out, i64 %t0
  store float %t7, float addrspace(1)* %t8, align 4
  ret void
}

attributes #0 = { argmemonly mustprogress nofree norecurse nosync nounwind willreturn "no-trapping-math"="true" }

!llvm.module.flags = !{!0, !1, !2, !3, !4, !5, !6}
!air.kernel = !{!13}
!air.compile_options = !{!7, !8}
!llvm.ident = !{!9}
!air.version = !{!10}
!air.language_version = !{!11}
!air.source_file_name = !{!12}

!0 = !{i32 2, !"SDK Version", [2 x i32] [i32 27, i32 0]}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 7, !"air.max_device_buffers", i32 31}
!3 = !{i32 7, !"air.max_constant_buffers", i32 31}
!4 = !{i32 7, !"air.max_threadgroup_buffers", i32 31}
!5 = !{i32 7, !"air.max_textures", i32 128}
!6 = !{i32 7, !"air.max_samplers", i32 16}
!7 = !{!"air.compile.denorms_disable"}
!8 = !{!"air.compile.fast_math_enable"}
!9 = !{!"BinC compiler v0.0.1 (bootstrap, in C)"}
!10 = !{i32 2, i32 9, i32 0}
!11 = !{!"Metal", i32 4, i32 1, i32 0}
!12 = !{!"binc"}
!14 = !{}
!15 = !{!16, !17, !18, !19}
!13 = !{void (float addrspace(1)*, float addrspace(1)*, float addrspace(1)*, i32)* @blend, !14, !15}
!16 = !{i32 0, !"air.buffer", !"air.location_index", i32 0, i32 1, !"air.read", !"air.address_space", i32 1, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"a"}
!17 = !{i32 1, !"air.buffer", !"air.location_index", i32 1, i32 1, !"air.read", !"air.address_space", i32 1, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"b"}
!18 = !{i32 2, !"air.buffer", !"air.location_index", i32 2, i32 1, !"air.write", !"air.address_space", i32 1, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"out"}
!19 = !{i32 3, !"air.thread_position_in_grid", !"air.arg_type_name", !"uint", !"air.arg_name", !"id"}
