; generated by binc — works as C, acts as Metal
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32"
target triple = "air64_v29-apple-macosx27.0.0"


define void @sc(float addrspace(1)* nocapture noundef %_a, float addrspace(1)* nocapture noundef %_out, float addrspace(2)* nocapture noundef readonly align 4 dereferenceable(4) %_k, float addrspace(2)* nocapture noundef readonly align 4 dereferenceable(4) %_lo, float addrspace(2)* nocapture noundef readonly align 4 dereferenceable(4) %_hi, i32 noundef %_id) local_unnamed_addr #0 {
  %t0 = zext i32 %_id to i64
  %t1 = alloca float, align 4
  %t6 = alloca i32, align 4
  %t7 = alloca float, align 4
  %t9 = alloca i32, align 4
  %t18 = alloca float, align 4
  %t2 = getelementptr inbounds float, float addrspace(1)* %_a, i64 %t0
  %t3 = load float, float addrspace(1)* %t2, align 4
  %t4 = load float, float addrspace(2)* %_k, align 4
  %t5 = fmul fast float %t3, %t4
  store float %t5, float* %t1, align 4
  store i32 3, i32* %t6, align 4
  %t8 = sitofp i32 0 to float
  store float %t8, float* %t7, align 4
  store i32 0, i32* %t9, align 4
  br label %bb0
bb0:
  %t10 = load i32, i32* %t9, align 4
  %t11 = load i32, i32* %t6, align 4
  %t12 = icmp slt i32 %t10, %t11
  br i1 %t12, label %bb1, label %bb3
bb1:
  %t13 = load float, float* %t7, align 4
  %t14 = load float, float* %t1, align 4
  %t15 = fadd fast float %t13, %t14
  store float %t15, float* %t7, align 4
  br label %bb2
bb2:
  %t16 = load i32, i32* %t9, align 4
  %t17 = add i32 %t16, 1
  store i32 %t17, i32* %t9, align 4
  br label %bb0
bb3:
  %t19 = load float, float* %t7, align 4
  %t20 = sitofp i32 3 to float
  %t21 = fdiv fast float %t19, %t20
  store float %t21, float* %t18, align 4
  %t22 = load float, float* %t18, align 4
  %t23 = load float, float addrspace(2)* %_lo, align 4
  %t24 = fcmp olt float %t22, %t23
  br i1 %t24, label %bb4, label %bb5
bb4:
  %t25 = getelementptr inbounds float, float addrspace(1)* %_out, i64 %t0
  store float %t23, float addrspace(1)* %t25, align 4
  br label %bb6
bb5:
  %t26 = load float, float* %t18, align 4
  %t27 = load float, float addrspace(2)* %_hi, align 4
  %t28 = fcmp ogt float %t26, %t27
  br i1 %t28, label %bb7, label %bb8
bb7:
  %t29 = getelementptr inbounds float, float addrspace(1)* %_out, i64 %t0
  store float %t27, float addrspace(1)* %t29, align 4
  br label %bb9
bb8:
  %t30 = load float, float* %t18, align 4
  %t31 = getelementptr inbounds float, float addrspace(1)* %_out, i64 %t0
  store float %t30, float addrspace(1)* %t31, align 4
  br label %bb9
bb9:
  br label %bb6
bb6:
  ret void
}

attributes #0 = { argmemonly mustprogress nofree norecurse nosync nounwind willreturn "no-trapping-math"="true" }

!llvm.module.flags = !{!0, !1, !2, !3, !4, !5, !6}
!air.kernel = !{!13}
!air.compile_options = !{!7, !8}
!llvm.ident = !{!9}
!air.version = !{!10}
!air.language_version = !{!11}
!air.source_file_name = !{!12}

!0 = !{i32 2, !"SDK Version", [2 x i32] [i32 27, i32 0]}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 7, !"air.max_device_buffers", i32 31}
!3 = !{i32 7, !"air.max_constant_buffers", i32 31}
!4 = !{i32 7, !"air.max_threadgroup_buffers", i32 31}
!5 = !{i32 7, !"air.max_textures", i32 128}
!6 = !{i32 7, !"air.max_samplers", i32 16}
!7 = !{!"air.compile.denorms_disable"}
!8 = !{!"air.compile.fast_math_enable"}
!9 = !{!"BinC compiler v0.0.1 (bootstrap, in C)"}
!10 = !{i32 2, i32 9, i32 0}
!11 = !{!"Metal", i32 4, i32 1, i32 0}
!12 = !{!"binc"}
!14 = !{}
!15 = !{!16, !17, !18, !19, !20, !21}
!13 = !{void (float addrspace(1)*, float addrspace(1)*, float addrspace(2)*, float addrspace(2)*, float addrspace(2)*, i32)* @sc, !14, !15}
!16 = !{i32 0, !"air.buffer", !"air.location_index", i32 0, i32 1, !"air.read", !"air.address_space", i32 1, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"a"}
!17 = !{i32 1, !"air.buffer", !"air.location_index", i32 1, i32 1, !"air.write", !"air.address_space", i32 1, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"out"}
!18 = !{i32 2, !"air.buffer", !"air.buffer_size", i32 4, !"air.location_index", i32 2, i32 1, !"air.read", !"air.address_space", i32 2, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"k"}
!19 = !{i32 3, !"air.buffer", !"air.buffer_size", i32 4, !"air.location_index", i32 3, i32 1, !"air.read", !"air.address_space", i32 2, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"lo"}
!20 = !{i32 4, !"air.buffer", !"air.buffer_size", i32 4, !"air.location_index", i32 4, i32 1, !"air.read", !"air.address_space", i32 2, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"hi"}
!21 = !{i32 5, !"air.thread_position_in_grid", !"air.arg_type_name", !"uint", !"air.arg_name", !"id"}
