; generated by binc — works as C, acts as Metal
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:64:64-f32:32:32-f64:64:64-v16:16:16-v24:32:32-v32:32:32-v48:64:64-v64:64:64-v96:128:128-v128:128:128-v192:256:256-v256:256:256-v512:512:512-v1024:1024:1024-n8:16:32"
target triple = "air64_v29-apple-macosx27.0.0"

%struct.Particle = type { float, float, float, float, float, float }

define void @step(%struct.Particle addrspace(1)* nocapture noundef %_p, float addrspace(2)* nocapture noundef readonly align 4 dereferenceable(4) %_dt, i32 noundef %_id) local_unnamed_addr #0 {
  %t0 = zext i32 %_id to i64
  %t1 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t2 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t1, i64 0, i32 3
  %t3 = load float, float addrspace(1)* %t2, align 4
  %t4 = load float, float addrspace(2)* %_dt, align 4
  %t5 = fmul fast float %t3, %t4
  %t6 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t7 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t6, i64 0, i32 0
  %t8 = load float, float addrspace(1)* %t7, align 4
  %t9 = fadd fast float %t8, %t5
  %t10 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t11 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t10, i64 0, i32 0
  store float %t9, float addrspace(1)* %t11, align 4
  %t12 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t13 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t12, i64 0, i32 4
  %t14 = load float, float addrspace(1)* %t13, align 4
  %t15 = fmul fast float %t14, %t4
  %t16 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t17 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t16, i64 0, i32 1
  %t18 = load float, float addrspace(1)* %t17, align 4
  %t19 = fadd fast float %t18, %t15
  %t20 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t21 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t20, i64 0, i32 1
  store float %t19, float addrspace(1)* %t21, align 4
  %t22 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t23 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t22, i64 0, i32 5
  %t24 = load float, float addrspace(1)* %t23, align 4
  %t25 = fmul fast float %t24, %t4
  %t26 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t27 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t26, i64 0, i32 2
  %t28 = load float, float addrspace(1)* %t27, align 4
  %t29 = fadd fast float %t28, %t25
  %t30 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %_p, i64 %t0
  %t31 = getelementptr inbounds %struct.Particle, %struct.Particle addrspace(1)* %t30, i64 0, i32 2
  store float %t29, float addrspace(1)* %t31, align 4
  ret void
}

attributes #0 = { argmemonly mustprogress nofree norecurse nosync nounwind willreturn "no-trapping-math"="true" }

!llvm.module.flags = !{!0, !1, !2, !3, !4, !5, !6}
!air.kernel = !{!13}
!air.compile_options = !{!7, !8}
!llvm.ident = !{!9}
!air.version = !{!10}
!air.language_version = !{!11}
!air.source_file_name = !{!12}

!0 = !{i32 2, !"SDK Version", [2 x i32] [i32 27, i32 0]}
!1 = !{i32 1, !"wchar_size", i32 4}
!2 = !{i32 7, !"air.max_device_buffers", i32 31}
!3 = !{i32 7, !"air.max_constant_buffers", i32 31}
!4 = !{i32 7, !"air.max_threadgroup_buffers", i32 31}
!5 = !{i32 7, !"air.max_textures", i32 128}
!6 = !{i32 7, !"air.max_samplers", i32 16}
!7 = !{!"air.compile.denorms_disable"}
!8 = !{!"air.compile.fast_math_enable"}
!9 = !{!"BinC compiler v0.0.1 (bootstrap, in C)"}
!10 = !{i32 2, i32 9, i32 0}
!11 = !{!"Metal", i32 4, i32 1, i32 0}
!12 = !{!"binc"}
!14 = !{}
!15 = !{!16, !17, !18}
!13 = !{void (%struct.Particle addrspace(1)*, float addrspace(2)*, i32)* @step, !14, !15}
!16 = !{i32 0, !"air.buffer", !"air.location_index", i32 0, i32 1, !"air.read_write", !"air.address_space", i32 1, !"air.arg_type_size", i32 24, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"Particle", !"air.arg_name", !"p"}
!17 = !{i32 1, !"air.buffer", !"air.buffer_size", i32 4, !"air.location_index", i32 1, i32 1, !"air.read", !"air.address_space", i32 2, !"air.arg_type_size", i32 4, !"air.arg_type_align_size", i32 4, !"air.arg_type_name", !"float", !"air.arg_name", !"dt"}
!18 = !{i32 2, !"air.thread_position_in_grid", !"air.arg_type_name", !"uint", !"air.arg_name", !"id"}
